# Generated by Django 4.2 on 2023-07-17 10:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('model_pn', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='category.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='category.subcategory')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=store.models.ProductGallery.get_file_path)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Gallery',
                'verbose_name_plural': 'Product Gallery',
                'db_table': 'product_gallery',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_type', models.CharField(blank=True, max_length=30, null=True)),
                ('type_of_control', models.CharField(blank=True, max_length=30, null=True)),
                ('display', models.CharField(blank=True, max_length=30, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=30, null=True)),
                ('special_features', models.CharField(blank=True, max_length=30, null=True)),
                ('loading_type', models.CharField(blank=True, max_length=30, null=True)),
                ('washing_capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('add_wash', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True)),
                ('eco_bubble', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True)),
                ('steam_wash', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True)),
                ('spin_speed', models.IntegerField(blank=True, null=True)),
                ('speed_adjustment', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True)),
                ('water_consumption_per_cycle', models.IntegerField(blank=True, null=True)),
                ('noise_level_wash', models.IntegerField(blank=True, null=True)),
                ('noise_level_spin', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='Height x Width x Depth', max_length=30, null=True)),
                ('weight', models.IntegerField(blank=True, help_text='kg', null=True)),
                ('varianty_month', models.IntegerField(blank=True, null=True)),
                ('automatic_cold_reservation_hours', models.IntegerField(blank=True, null=True)),
                ('number_of_shelf', models.IntegerField(blank=True, null=True)),
                ('door_pocket', models.IntegerField(blank=True, null=True)),
                ('freezer_location', models.CharField(blank=True, max_length=30, null=True)),
                ('egg_container', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True)),
                ('freezer_net_capacity', models.IntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='store.product')),
            ],
            options={
                'db_table': 'product_feature',
            },
        ),
    ]
