# Generated by Django 4.2 on 2023-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='productfeature',
            name='climate_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
