# Generated by Django 4.2 on 2023-07-12 12:01

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productgallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to=store.models.ProductGallery.get_file_path),
        ),
    ]
