# Generated by Django 4.2 on 2023-07-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productfeatures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='created_by',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
    ]
