# Generated by Django 4.2 on 2023-07-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'sub category', 'verbose_name_plural': 'Sub Categories'},
        ),
    ]
