# Generated by Django 4.2 on 2023-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
